name: ci
on: [push, pull_request]
jobs:
  data:
    env:
      NFPM_VERSION: 2.2.3
      ZEF_VERSION: 0.11.2
      RAKUDO_VERSION: 2020.12
      NQP_VERSION: 2020.12
      MOARVM_VERSION: 2020.12
      MOARVM_REPO: https://github.com/MoarVM/MoarVM.git"
      NQP_REPO: https://github.com/perl6/nqp.git"
      RAKUDO_REPO: https://github.com/rakudo/rakudo.git"
      ZEF_REPO: https://github.com/ugexe/zef.git"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get nfpm
        run: |
          curl -sSL https://github.com/goreleaser/nfpm/releases/download/v$NFPM_VERSION/nfpm_${NFPM_RELEASE}_Linux_x86_64.tar.gz -o nfpm.tar.gz
      - name: Get Rakudo
        run: |
          curl -sSL -o moarvm.tar.gz https://github.com/MoarVM/MoarVM/releases/download/$MOARVM_VERSION/MoarVM-${MOARVM_VERSION}.tar.gz
          curl -sSL -o nqp.tar.gz https://github.com/Raku/nqp/releases/download/$NQP_VERSION/nqp-${NQP_VERSION}.tar.gz
          curl -sSl -o rakudo.tar.gz https://github.com/rakudo/rakudo/releases/download/$RAKUDO_VERSION/rakudo-${RAKUDO_VERSION}.tar.gz
          curl -sSL -o zef.tag.gz https://github.com/ugexe/zef/archive/v${ZEF_VERSION}.tar.gz
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: checkout
          path: ${{ github.workspace }}
  package:
    needs: data
    env:
      ZEF_VERSION: v0.11.2
      RAKUDO_VERSION: 2020.12
      NQP_VERSION: 2020.12
      MOARVM_VERSION: 2020.12
      REVISION: 01
      MAINTAINER: "Claudio Ramirez <pub.claudio@gmail.com>"
      INSTALL_ROOT: /opt/rakudo-pkg
    strategy:
      matrix:
        image: [
          "alpine:3.10", "alpine:3.11", "alpine:3.12", "alpine:3.13",
          "alpine:edge",
          "centos:7", "centos:8",
          "registry.access.redhat.com/ubi7-minimal",
          "registry.access.redhat.com/ubi8-minimal",
          "debian:9-slim", "debian:10-slim",
          "debian:testing-slim", "debian:unstable-slim",
          "debian:experimental", 
          "fedora:31", "fedora:32", "fedora:rawhide",
          "opensuse/leap:15.2", "opensuse/tumbleweed",
          "ubuntu:16.04", "ubuntu:18.04", "ubuntu:20.04", "ubuntu:20.10",
        ]
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    steps:
      - name: Download checkout
        uses: actions/download-artifact@v2
        with:
          name: checkout
      - name: Run in container
        run: |
          cat /etc/*release
          chmod +x nfpm
          ./nfpm -v

