name: ci
on: [push, pull_request]
jobs:
  data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download nfpm, MoarVM, nqp, Rakudo and zef
        run: ./actions/00-download.sh
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: checkout
          #path: ${{ github.workspace }}
          path: |
            actions/*
            include/*
            *.tar.gz
  package:
    needs: data
    env:
      MAINTAINER: "Claudio Ramirez <pub.claudio@gmail.com>"
      INSTALL_ROOT: /opt/rakudo-pkg
      CONFIG_SHELL: /bin/bash
    strategy:
      matrix:
        image: [
       #   "alpine:3.10", "alpine:3.11", "alpine:3.12",
       #   "alpine:3.13", "alpine:edge",
       #   "centos:7", "centos:8",
          "registry.access.redhat.com/ubi7-minimal",
       #   "registry.access.redhat.com/ubi8-minimal",
       #   "debian:9-slim", "debian:10-slim", "debian:testing-slim",
       #   "debian:unstable-slim", "debian:experimental", 
       #   "fedora:31", "fedora:32", "fedora:rawhide",
       #   "opensuse/leap:15.2", "opensuse/tumbleweed",
       #   "ubuntu:16.04", "ubuntu:18.04", "ubuntu:20.04",
       #   "ubuntu:20.10", "ubuntu:devel",
        ]
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    steps:
      - name: Download checkout
        uses: actions/download-artifact@v2
        with:
          name: checkout
      - name: Create build environment 
        env:
          IMAGE: ${{ matrix.image }}
        run: |
          chmod +x actions/*
          ./actions/01-setup_env.sh
      - name: Build
        run: |
          set -xv
          ./actions/02-build.sh
