name: ci
on: [push, pull_request]
jobs:
  data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get nfpm and Rakudo
        run: |
          . ./versions.sh
          curl -sSL https://github.com/goreleaser/nfpm/releases/download/v$NFPM_VERSION/nfpm_${NFPM_RELEASE}_Linux_x86_64.tar.gz -o nfpm.tar.gz
          curl -sSL -o moarvm.tar.gz https://github.com/MoarVM/MoarVM/releases/download/$MOARVM_VERSION/MoarVM-${MOARVM_VERSION}.tar.gz
          curl -sSL -o nqp.tar.gz https://github.com/Raku/nqp/releases/download/$NQP_VERSION/nqp-${NQP_VERSION}.tar.gz
          curl -sSl -o rakudo.tar.gz https://github.com/rakudo/rakudo/releases/download/$RAKUDO_VERSION/rakudo-${RAKUDO_VERSION}.tar.gz
          curl -sSL -o zef.tar.gz https://github.com/ugexe/zef/archive/v${ZEF_VERSION}.tar.gz
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: checkout
          #path: ${{ github.workspace }}
          path: |
            *.tar.gz
            *.sh
  package:
    needs: data
    env:
      MAINTAINER: "Claudio Ramirez <pub.claudio@gmail.com>"
      INSTALL_ROOT: /opt/rakudo-pkg
    strategy:
      matrix:
        image: [
          "alpine:3.10", "alpine:3.11", "alpine:3.12", "alpine:3.13",
          "alpine:edge",
#          "centos:7", "centos:8",
#          "registry.access.redhat.com/ubi7-minimal",
#          "registry.access.redhat.com/ubi8-minimal",
          "debian:9-slim", "debian:10-slim",
          "debian:testing-slim", "debian:unstable-slim",
          "debian:experimental", 
#          "fedora:31", "fedora:32", "fedora:rawhide",
#          "opensuse/leap:15.2", "opensuse/tumbleweed",
          "ubuntu:16.04", "ubuntu:18.04", "ubuntu:20.04", "ubuntu:20.10",
          "ubuntu:devel",
        ]
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    steps:
      - name: Download checkout
        uses: actions/download-artifact@v2
        with:
          name: checkout
      - name: Create build environment 
        run: |
          chmod +x *.sh
          ./build_env.sh
      - name: Check environment variables
        run: |
          . ./versions.sh
          env | grep OS

