name: ci
on: [push, pull_request]
jobs:
  package:
    env:
      ZEF_VERSION: v0.11.2
      RAKUDO_VERSION: 2020.12
      NQP_VERSION: 2020.12
      MOARVM_VERSION: 2020.12
      REVISION: 01
      MAINTAINER: "Claudio Ramirez <pub.claudio@gmail.com>"
    strategy:
      matrix:
        image: [
          "alpine:3.10", "alpine:3.11", "alpine:3.12", "alpine:3.13",
          "alpine:edge",
          "centos:6", "centos:7", "centos:8",
          "registry.access.redhat.com/rhel6",
          "registry.access.redhat.com/ubi7-minimal",
          "registry.access.redhat.com/ubi8-minimal",
          "debian:9.2@sha256:\
4599b85efe839220e3c00b5d380910fbe968ffe933a9155a6f013fb416ffa1f1",          
          "debian:9-slim", "debian:10-slim",
          "debian:testing-slim", "debian:unstable-slim",
          "debian:experimental", 
          "fedora:31", "fedora:32", "fedora:rawhide",
          "opensuse/leap:15.2", "opensuse/tumbleweed",
          "ubuntu:16.04", "ubuntu:18.04", "ubuntu:20.04", "ubuntu:20.10",
        ]
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Run in container
      run: pwd && ls -la && cat /etc/*release
