name: ci
on: [push, pull_request]
jobs:
  package:
    env:
      ZEF_VERSION: v0.11.2
      RAKUDO_VERSION: 2020.12
      NQP_VERSION: 2020.12
      MOARVM_VERSION: 2020.12
      REVISION: 01
      MAINTAINER: "Claudio Ramirez <pub.claudio@gmail.com>"
    strategy:
      matrix:
        image: [
          "alpine:3.10", "alpine:3.11", "alpine:3.12", "alpine:3.13",
          "alpine:edge",
          "centos:6", "centos:7", "centos:8",
          "registry.access.redhat.com/rhel6",
          "registry.access.redhat.com/ubi7-minimal",
          "registry.access.redhat.com/ubi8-minimal",
          "debian:9.2@sha256:3ef30aac6c45de2289291398a19f92733143fd4de42d6be02f67f2e07755e5eb",
          "debian:9-slim", "debian:10-slim",
          "debian:testing-slim", "debian:unstable-slim",
          "debian:experimental", 
        ]
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    steps:
    - name: Run in container
      run: cat /etc/*release
